[package]
name = 'builder'
version = '0.1.0'
authors = ['Sam Denty <samddenty@gmail.com>']
edition = '2018'
[profile.release]
opt-level = 'z'
lto = 'thin'

[lib]
crate-type = [
    'cdylib',
    'rlib',
]

[features]
default = ['wee_alloc']

[dependencies]
js-sys = '0.3.32'
lazy_static = '1.4.0'
wasm-bindgen = '0.2'
derivative = '1.0.3'
maplit = '1.0.2'

[dependencies.console_error_panic_hook]
version = '0.1.1'
optional = true

[dependencies.web-sys]
version = '0.3'
features = ['console']

[dependencies.wee_alloc]
version = '0.4.2'
optional = true

[dev-dependencies]
wasm-bindgen-test = '0.2'
